# Arena PvP
# By Stoneharry

# The name of the world file (e.g: world)
WorldName: arena

homeWorld: world
homeX: -296
homeY: 80
homeZ: 307

blueX: 0
blueY: 5
blueZ: -21

redX: -6
redY: 5
redZ: 14

deadX: -5
deadY: 4
deadZ: 30