# Arena PvP
# By Stoneharry

# The name of the world file (e.g: world)
WorldName: arena

homeWorld: world
homeX: -296
homeY: 80
homeZ: 307

deadX: -5
deadY: 4
deadZ: 30

# Number of arenas - must be > 1
numArenas: 7

1blueX: 0
1blueY: 5
1blueZ: -21
1redX: -6
1redY: 5
1redZ: 14

2blueX: 15
2blueY: 9
2blueZ: 20
2redX: 19
2redY: 8
2redZ: 56

3blueX: 22
3blueY: 6
3blueZ: -38
3redX: 67
3redY: 6
3redZ: 13

4blueX: -20
4blueY: 28
4blueZ: -56
4redX: 12
4redY: 28
4redZ: -28

5blueX: -18
5blueY: 6
5blueZ: 19
5redX: -18
5redY: 6
5redZ: 73

6blueX: -5
6blueY: 5
6blueZ: 84
6redX: 15
6redY: 5
6redZ: 63

7blueX: 34
7blueY: 5
7blueZ: 92
7redX: 34
7redY: 5
7redZ: 63